id: intel471 Malware Feed Test
version: 4
fromversion: 5.0.0
vcShouldKeepItemLegacyProdMachine: false
name: intel471 Malware Feed Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dd64f056-2cb0-4e21-8b79-c48411c320ea
    type: start
    task:
      id: dd64f056-2cb0-4e21-8b79-c48411c320ea
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 630,
          "y": -150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 1537b6e5-f1ec-41b1-8762-54d713b955d5
    type: condition
    task:
      id: 1537b6e5-f1ec-41b1-8762-54d713b955d5
      version: -1
      name: is instance active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Intel471 Malware Feed
                accessor: state
            iscontext: true
          right:
            value:
              simple: active
    view: |-
      {
        "position": {
          "x": 630,
          "y": 20
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: f5e3ba93-a132-458e-80fb-5a5591424e8f
    type: title
    task:
      id: f5e3ba93-a132-458e-80fb-5a5591424e8f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 630,
          "y": 610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: e9cb2fb8-b0ea-4fec-89c8-37571aa2749a
    type: regular
    task:
      id: e9cb2fb8-b0ea-4fec-89c8-37571aa2749a
      version: -1
      name: intel471-get-indicators
      description: Gets the feed indicators.
      script: '|||intel471-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      limit:
        simple: ${inputs.Limit}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 970,
          "y": 240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 825,
        "width": 720,
        "x": 630,
        "y": -150
      }
    }
  }
inputs:
- key: Limit
  value: {}
  required: false
  description: How many results to fetch
  playbookInputQuery: null
outputs: []
